### ISSUE TITLE
[FAILED] Failed to start Raise network interfaces.

### ISSUE THREAD

**Issue by fpgasdr** [Stavros/ebaz4205#1]
hi,

I have the ebaz4205 without clock crystal so no sure if this image will work the ethernet port.

what should I could do to make it works?.

thanks

**Comment by Stavros** [comment]
Hi @eljuligallego ,

The specific image available for download in my repo is built without the PL clock source, as my board has the external Y3 25MHz clock installed.

I guess there are two options:

1. physical solder the missing crystal, or
2. try to rebuilt the base Petalinux image and the PYNQ overlay without skipping the PL clock source, following the [guide](https://webuiltawallwebuiltthepyramids.blogspot.com/2021/01/ebaz4205-petalinux-installation.html).

Hope the above helps.

**Comment by Stavros** [comment]
Closing as there are no further comments.
